### PR TITLE
Fix: only add Prefix self when it's Dir.

### PR DESCRIPTION
**Pull request by akang943578**
Only need to add self prefix path if it's Dir when listBucket. Sorry for this PR is a fix to previous PR which tested not enough with edge cases. Please merge and make a new release based on it.

There is also some code changes on alist-org/alist, I will create new PR for it based on the new Release. 

I will make codes changes , and depend new release version of alist-org/gofakes3 in alist-org/alist together in a single PR.

### CODE REVIEW

**Comment by akang943578** [comment]
@itsHenry35 Can you help to review it?

**Comment by itsHenry35** [comment]
Pls give me an example of the edge case.

**Comment by akang943578** [comment]
> Pls give me an example of the edge case.

Here's the scenario:
Using WinSCP to copy a local directory to S3, suppose the local directory is as follows: aaa/1.txt
Step 1: listBucket for aaa/ works fine; contents only contains a Content object symbolizing this directory.
Step 2: listBucket for aaa/1.txt also has contents containing a Content object symbolizing this file, but this is a file, causing the page to indicate that aaa/1.txt already exists, even though it doesn't.

Therefore, a conditional filter needs to be added. A phantom Content should only be created when performing a listBucket operation on a directory.

**Comment by itsHenry35** [comment]
New release done. https://github.com/alist-org/gofakes3/releases/tag/v0.0.7

**Pull request merged**
